cc_library(
    name = "knowledge_function_definition",
    hdrs = [
        "knowledge_function_definition.hpp",
        "linear_knowledge_function_definition.hpp"
    ],
    deps = [
        "@bark_project//bark/commons/params:params"
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)