cc_library(
    name = "heuristics",
    hdrs = ["domain_heuristic.hpp"],
    copts = ["-Iexternal/bark_project"],
    deps= [
        "@bark_project//bark:include",
        "@mamcts_project//mcts:mamcts"
    ],
    visibility = ["//visibility:public"],
)