py_library(
    name = "behavior_space",
    srcs = [
     "behavior_space.py",
     "knowledge_function_definitions.py"
     ],
    data = ['@bark_project//bark:generate_core'],
    visibility = ["//visibility:public"],
)