name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark-ml:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: bash ./util/setup_test_venv.sh
      - name: Entering the virtual python environment..
        run: . ./bark_mcts/python_wrapper/venv/bin/activate 
      - name: Installing Pytorch venv..
        run: pip install --target=./bark_mcts/python_wrapper/venv/lib/python3.7/site-packages torch==1.9.0+cpu torchvision -f https://download.pytorch.org/whl/torch_stable.html
      - name: Installing Pytorch global..
        run: pip install torch==1.9.0+cpu torchvision -f https://download.pytorch.org/whl/torch_stable.html
      - name: Add torch environment variable
        run: export LD_LIBRARY_PATH=./bark_mcts/python_wrapper/venv/lib/python3.7/site-packages/torch/lib/
      - name: Running tests
        run: bazel test //...
